import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layouts/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/bgPic.png')] bg-cover bg-center bg-no-repeat`}
      >
        <div className="w-screen h-screen grid grid-cols-[250px_1fr] gap-4 backdrop-blur-[100px] bg-white/10">
          <Sidebar />
          <div className="py-20 pt-3">{children}</div> 
        </div>
      </body>
    </html>
  );
}
