export const wilaya = [
    "Adrar",
    "Chlef",
    "Laghouat",
    "Oum El Bouaghi",
    "Batna",
    "Béjaïa",
    "Biskra",
    "Béchar",
    "Blida",
    "Bouira",
    "Tamanrasset",
    "Tébessa",
    "Tlemcen",
    "Tiaret",
    "Tizi Ouzou",
    "Alger",
    "Djelfa",
    "Jijel",
    "Sétif",
    "Saïda",
    "Skikda",
    "Sidi Bel Abbès",
    "Annaba",
    "Guelma",
    "Constantine",
    "Médéa",
    "Mostaganem",
    "M'Sila",
    "Mascara",
    "Ouargla",
    "Oran",
    "El Bayadh",
    "Illizi",
    "Bordj Bou Arréridj",
    "Boumerdès",
    "El Tarf",
    "Tindouf",
    "Tissemsilt",
    "El Oued",
    "Khenchela",
    "Souk Ahras",
    "Tipaza",
    "Mila",
    "Aïn Defla",
    "Naâma",
    "Aïn Témouchent",
    "Ghardaïa",
    "Relizane",
    "El M'ghair",
    "El Menia",
    "Ouled Djellal",
    "Bordj Baji Mokhtar",
    "Beni Abbes",
    "Timimoun",
    "Touggourt",
    "Djanet",
    "In Salah",
    "In Guezzam",
    "In Amguel",
    "In Zghmir",
    "In Ghar",
    "In M'guel",
    "In Abguel",
    "In Ezzane",
    "In Timedouine",
    "In Zouerate",
]

export const Commune = {
    "Adrar": [
        "Adrar",
        "Tamest",
        "Charouine",
        "Reggane",
        "Talmine",
    ],
    "Chlef": [
        "Chlef",
        "Ténès",
        "Beni Haoua",
        "Tadjena",
        "Taougrite",
    ],
    "Laghouat": [
        "Laghouat",
        "Ksar El Hirane",
        "Aflou",
        "El Assafia",
        "Oued Morra",
    ],
    "Oum El Bouaghi": [
        "Oum El Bouaghi",
        "Aïn Beïda",
        "Aïn M'Lila",
        "Sigus",
        "El Amiria",
    ],
}

export const speciality = [
    "speciality 1",
    "speciality 2",
    "speciality 3",
]

export const language = [
    "Arabic",
    "English",
    "French",
]

export const phoneCode = [
    "+213",
    "+1",
    "+33",
    "+49",
    "+44",
    "+81",
    "+86",
    "+7",
]
